# Numpy library
## fast, less memory and convient rather than list.
## using this we can create n.dimensionl array.

In [2]:
import numpy as np

In [35]:
a = np.array([1,2]) # 1D arrray
print(a)

[1 2]


In [36]:
a = np.array([[1,2],[3,4],[5,6]]) # 2d array
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [54]:
print(a.ndim,'\n')  # it will give dimension size

print(a.dtype,'\n')

print(a.size,'\n')  # element size of array

print(a.itemsize,'\n') # gives itemsize

print(a.shape)



2 

complex128 

6 

16 

(3, 2)


#### change datatype

In [49]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
print(a,'\n')

a = np.array([[1,2],[3,4],[5,6]]).astype('float') # it can convert the datatype of array
print(a,'\n')

a = np.array([[1,2],[3,4],[5,6]]).astype('complex')
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]] 

[[1. 2.]
 [3. 4.]
 [5. 6.]] 

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


### craete array(matrix) of zeros and ones

In [61]:
a = np.zeros((3,4))
print(a,'\n')

a = np.zeros((3,4), int)
print(a,'\n')

a = np.zeros((3,4)).astype('int')
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [64]:
a = np.ones((3,4))
print(a,'\n')

a = np.ones((3,4),int)
print(a,'\n')
a = np.ones([3,4]).astype('int')
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#### create linear sequence number

In [70]:
a = np.linspace(1,5,20) # To generate linear Sequence number
print(a,'\n')

a = np.linspace(1,5,5)
print(a,'\n')

a = np.linspace(1,5,5).astype('int')
print(a)


[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ] 

[1. 2. 3. 4. 5.] 

[1 2 3 4 5]


In [71]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [72]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a.ravel() # it will return new array in 1d

array([1, 2, 3, 4, 5, 6])

### mathmatical function

In [76]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
print(a,'\n')

a.min()

[[1 2]
 [3 4]
 [5 6]]


1

In [77]:
a.max()

6

In [86]:
print(a.sum())

print(a.sum(axis = 1))
print(a.sum(axis = 0))

21
[ 3  7 11]
[ 9 12]


In [87]:
print(np.mean(a))

a.mean()

3.5


3.5

In [88]:
print(a.std())

np.std(a)

1.707825127659933


1.707825127659933

In [94]:
print(np.sqrt(a),'\n')

print(np.sqrt(a).astype('int'))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]] 

[[1 1]
 [1 2]
 [2 2]]


In [95]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b,'\n')
print(b-a,'\n')
print(a*b,'\n')
print(b/a,'\n')

[[ 6  8]
 [10 12]] 

[[4 4]
 [4 4]] 

[[ 5 12]
 [21 32]] 

[[5.         3.        ]
 [2.33333333 2.        ]] 



In [96]:
print(a.dot(b))

[[19 22]
 [43 50]]


### Slicing & indexing

In [97]:
a = np.array([[6,7,8],[1,2,3],[9,3,4]])
print(a)

[[6 7 8]
 [1 2 3]
 [9 3 4]]


In [101]:
print(a[1,2],'\n')

print(a[2,2],'\n')

print(a[0,2])

3 

4 

8


In [102]:
print(a[0:2,2])

[8 3]


In [104]:
print(a[:,1:],'\n')

print(a[:,1:3])

[[7 8]
 [2 3]
 [3 4]] 

[[7 8]
 [2 3]
 [3 4]]


In [105]:
print(a)

[[6 7 8]
 [1 2 3]
 [9 3 4]]


In [108]:
print(a[2,0:2],'\n')

print(a[-1,0:2])

[9 3] 

[9 3]


### iteration in array

In [109]:
import numpy as np
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
print(a)

[[6 7 8]
 [1 2 3]
 [9 3 2]]


In [110]:
for i in a:
    print(i)

[6 7 8]
[1 2 3]
[9 3 2]


In [111]:
for i in a.flatten():
    print(i)

6
7
8
1
2
3
9
3
2


## stacking and splitting

#### stacking  

In [114]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a,'\n')
print(b)

[[0 1]
 [2 3]
 [4 5]] 

[[ 6  7]
 [ 8  9]
 [10 11]]


In [115]:
# vstack (vertical stacking)
print(np.vstack((a,b)))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [117]:
# horizontal stacking
print(np.hstack((a,b)))

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


#### splitting 

In [118]:
a = np.arange(30).reshape(2,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [133]:
# vsplit

r = np.vsplit(a,2)
print(r)

print(r[0],'\n')

print(r[1],'\n')



[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]] 

[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 



In [136]:
# hsplit
r = np.hsplit(a,3)
print(r,'\n')

print(r[0],'\n')

print(r[1],'\n')

print(r[2],'\n')

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])] 

[[ 0  1  2  3  4]
 [15 16 17 18 19]] 

[[ 5  6  7  8  9]
 [20 21 22 23 24]] 

[[10 11 12 13 14]
 [25 26 27 28 29]] 



### indexing with boolean

In [138]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [140]:
b = a>4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [141]:
print(a[b])

[ 5  6  7  8  9 10 11]


In [142]:
a[b] = -1
print(a)

[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


## numpy array using nditer 

In [146]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a,'\n')
for cell in a.flatten():
    print(cell)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

0
1
2
3
4
5
6
7
8
9
10
11


In [149]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [148]:
for x in np.nditer(a,order = 'C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [150]:
for x in np.nditer(a, order = 'F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [151]:
for x in np.nditer(a, order = 'F', flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [152]:
for x in np.nditer(a, op_flags = ['readwrite']):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [156]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
for i,j in np.nditer([a,b]):
    print(i,j)

0 6
1 7
2 8
3 9
4 10
5 11


In [158]:
# np.unique = remove duplicity from numpy array

a = np.array([[1,2],[3,4],[1,4],[4,5]])
print(np.unique(a))

[1 2 3 4 5]


## np.append 

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.append(a,b),'\n')

print(np.append(a,b,axis = 1))

[1 2 3 4 5 6 7 8] 

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.aapend())